import React, { useState } from 'react';
import {
  Database,
  CloudRain,
  Mountain,
  History,
  ShieldCheck,
  AlertTriangle,
  Code2,
  FileText,
  Radio,
  BookOpen,
  Search,
  CheckCircle,
  HelpCircle,
  Activity,
  Layers,
} from 'lucide-react';

interface GlossaryItem {
  term: string;
  category: 'Geospatial' | 'Hydrology' | 'Geology' | 'System & Data' | 'Risk Analysis';
  simpleExplanation: string;
  technicalContext: string;
}

const GLOSSARY_TERMS: GlossaryItem[] = [
  {
    term: 'Landslide Susceptibility',
    category: 'Risk Analysis',
    simpleExplanation: 'The likelihood of a landslide occurring in an area based on its natural physical characteristics (how steep, what kind of rock, how wet the ground is).',
    technicalContext: 'A relative spatial probability surface generated by combining static terrain factors with hydrological and geological conditioning indices.',
  },
  {
    term: 'Risk Score (0–100)',
    category: 'Risk Analysis',
    simpleExplanation: 'A single numerical rating calculated by LANDGUARD AI from 0 to 100 representing how severe the landslide hazard conditions are right now.',
    technicalContext: 'A weighted linear combination of normalized physical factor sub-scores: Rainfall (35%), Slope (30%), Historical (20%), and Terrain (15%).',
  },
  {
    term: 'Risk Level (Low, Moderate, High, Critical)',
    category: 'Risk Analysis',
    simpleExplanation: 'Actionable classification bands: Low (0–25), Moderate (26–50), High (51–75), and Critical (76–100) determining what response actions are needed.',
    technicalContext: 'Discrete decision-support operational intervals mapped from continuous composite susceptibility values for emergency management escalation.',
  },
  {
    term: 'Hotspot',
    category: 'Risk Analysis',
    simpleExplanation: 'A dangerous cluster point where multiple dangerous factors occur at once: heavy rainfall, steep slopes, and previous landslide scars.',
    technicalContext: 'A spatial condition flag triggered when slope score ≥ 60 AND rainfall score ≥ 55, or composite score ≥ 72.',
  },
  {
    term: 'Slope (Gradient in Degrees °)',
    category: 'Geospatial',
    simpleExplanation: 'How steep the hillside is. Flat ground is 0°, a gentle hill is 15°, and a steep mountain cliff is 35° or steeper.',
    technicalContext: 'First derivative of the digital elevation model (DEM) measuring maximum rate of elevation change across a 30m grid cell.',
  },
  {
    term: 'Elevation (Meters Above Sea Level)',
    category: 'Geospatial',
    simpleExplanation: 'Height above sea level in meters. Higher mountain peaks often experience different freeze-thaw and heavier cloudburst rains.',
    technicalContext: 'Orthometric altitude recorded in meters from satellite radar interferometry (SRTM/ASTER).',
  },
  {
    term: 'Aspect',
    category: 'Geospatial',
    simpleExplanation: 'The compass direction a mountain slope faces (such as North, South, East, or West). South-facing slopes in the Himalayas receive more direct sunlight and monsoon wind.',
    technicalContext: 'Compass bearing (0–360°) of steepest slope downslope direction, conditioning moisture retention and weathering exposure.',
  },
  {
    term: 'Terrain',
    category: 'Geospatial',
    simpleExplanation: 'The physical shape, contours, steepness, and ruggedness of the land surface.',
    technicalContext: 'Macroscopic geomorphometry encompassing elevation, slope gradient, aspect, curvature, and dissection indices.',
  },
  {
    term: 'Terrain Ruggedness Index (TRI)',
    category: 'Geospatial',
    simpleExplanation: 'A measure of how rough or broken a mountain landscape is compared to smooth, flat terrain.',
    technicalContext: 'Quantified elevation variance among adjacent 30m DEM raster cells, reflecting mechanical shear stress and drainage incisement.',
  },
  {
    term: 'Digital Elevation Model (DEM)',
    category: 'Geospatial',
    simpleExplanation: 'A 3D computer model of the Earth’s surface showing heights and mountain shapes in a grid of numbers.',
    technicalContext: 'Raster array where each grid cell contains an orthometric elevation value representing the bare-earth topography.',
  },
  {
    term: 'SRTM (Shuttle Radar Topography Mission)',
    category: 'Geospatial',
    simpleExplanation: 'A NASA space radar mission that mapped Earth’s mountains at 30-meter detail. LANDGUARD AI uses this as a static terrain baseline.',
    technicalContext: '1-arc-second (~30m) global digital elevation dataset acquired using C-band spaceborne radar interferometry.',
  },
  {
    term: 'ASTER (Advanced Spaceborne Thermal Emission and Reflection Radiometer)',
    category: 'Geospatial',
    simpleExplanation: 'A satellite sensor flown by NASA and Japan used alongside SRTM to verify mountain elevations and slope angles in the Himalayas.',
    technicalContext: 'Global digital elevation model (GDEM v3) stereo-correlated from nadir and backward-looking optical telescope infrared pairs.',
  },
  {
    term: 'Lithology',
    category: 'Geology',
    simpleExplanation: 'The physical and mineral characteristics of rocks in an area (hard granite vs. soft crumbly shale).',
    technicalContext: 'Geological rock composition, crystalline structure, degree of jointing, weathering crust, and mechanical shear strength.',
  },
  {
    term: 'Phyllite',
    category: 'Geology',
    simpleExplanation: 'A fragile, layered metamorphic rock common in Sikkim and Arunachal Pradesh that easily splits into thin sheets when soaked in rainwater.',
    technicalContext: 'Foliated metamorphic rock rich in aligned mica and chlorite crystals exhibiting pronounced fissility and planar slide planes.',
  },
  {
    term: 'Shale',
    category: 'Geology',
    simpleExplanation: 'A soft sedimentary rock formed from ancient mud. When heavy rains soak shale slopes, they quickly turn into slippery mud and collapse.',
    technicalContext: 'Fine-grained fissile sedimentary rock susceptible to rapid slaking, swelling, and residual shear strength reduction under positive pore pressure.',
  },
  {
    term: 'Land Cover',
    category: 'Geospatial',
    simpleExplanation: 'What is on top of the soil — such as dense natural forests, farmland, road construction cuts, or buildings.',
    technicalContext: 'Biophysical surface mantle classifying vegetation canopy root cohesion versus un-vegetated anthropic excavation slopes.',
  },
  {
    term: 'Antecedent Rainfall',
    category: 'Hydrology',
    simpleExplanation: 'The rain that fell several days BEFORE today. If the ground is already soaked from 3 days of rain, even a small new storm can trigger a slide.',
    technicalContext: 'Cumulative preceding precipitation ($R_{72h}$) that diminishes matric suction and elevates sub-surface soil moisture toward saturation.',
  },
  {
    term: '72-Hour Rainfall',
    category: 'Hydrology',
    simpleExplanation: 'The total amount of rainfall measured over the last three full days (in millimeters). In the Himalayas, >180mm is considered critical.',
    technicalContext: 'A key empirical landslide trigger threshold measuring cumulative pore-water pressure buildup along colluvial bed contacts.',
  },
  {
    term: 'Rainfall Rate',
    category: 'Hydrology',
    simpleExplanation: 'How fast it is raining right now, measured in millimeters per hour (mm/h). More than 15–20 mm/h is a torrential cloudburst.',
    technicalContext: 'Instantaneous hourly precipitation intensity ($R_{current}$) governing infiltration-excess overland flow and topsoil liquefaction.',
  },
  {
    term: 'Spatial Proximity',
    category: 'Geospatial',
    simpleExplanation: 'How close one place is to another on a map, measured in meters or kilometers.',
    technicalContext: 'Geodesic or Euclidean distance calculation between hazard source centroids and vulnerable human or structural receptors.',
  },
  {
    term: 'Spatial Decay',
    category: 'Risk Analysis',
    simpleExplanation: 'The scientific rule that danger decreases as you get farther away from an old landslide or steep cliff.',
    technicalContext: 'Mathematical attenuation function reducing susceptibility influence with increasing radial distance from known shear failure planes.',
  },
  {
    term: 'Buffer Analysis',
    category: 'Geospatial',
    simpleExplanation: 'Drawing a virtual safety circle (such as 2.5 km) around a mountain slope to count all the homes, schools, and hospitals inside it.',
    technicalContext: 'Geoprocessing operation creating a radial zone of specified distance around a spatial feature to perform impact intersection queries.',
  },
  {
    term: 'Geospatial / GIS',
    category: 'Geospatial',
    simpleExplanation: 'Geographic Information Systems — computer software that stores, maps, and analyzes data linked to real places on Earth.',
    technicalContext: 'Spatial data infrastructure framework for acquiring, managing, querying, and visualizing coordinate-referenced cartographic entities.',
  },
  {
    term: 'Latitude & Longitude',
    category: 'Geospatial',
    simpleExplanation: 'The worldwide GPS grid coordinates that pinpoint an exact spot on Earth (North/South degrees and East/West degrees).',
    technicalContext: 'Spherical angular coordinates referencing location on the WGS84 geographic datum relative to the Equator and Prime Meridian.',
  },
  {
    term: 'Infrastructure Exposure',
    category: 'Risk Analysis',
    simpleExplanation: 'Which highways, bridges, power lines, schools, and hospitals are in danger if a slope fails.',
    technicalContext: 'Tally and spatial intersection of critical societal assets located within empirical debris runout or cut-slope isolation corridors.',
  },
  {
    term: 'Impact Priority',
    category: 'Risk Analysis',
    simpleExplanation: 'A formula that combines slope danger with how many people and buildings are nearby to tell emergency teams where to go first.',
    technicalContext: 'Composite priority index weighting physical susceptibility (45%), infrastructure count (30%), and human population count (25%).',
  },
  {
    term: 'Risk Assessment',
    category: 'Risk Analysis',
    simpleExplanation: 'The complete process of measuring how dangerous an area is and who could be harmed.',
    technicalContext: 'Systematic quantitative and qualitative evaluation combining hazard probability, element vulnerability, and exposure value.',
  },
  {
    term: 'Early Warning',
    category: 'Risk Analysis',
    simpleExplanation: 'Alerting authorities and citizens about high danger before an event occurs so preventative steps can be taken.',
    technicalContext: 'Actionable bulletin dispatch prior to threshold breach enabling pre-positioning of rescue teams and traffic diversions.',
  },
  {
    term: 'Decision Support',
    category: 'System & Data',
    simpleExplanation: 'Software tools that give clear facts and suggestions to help officials make better, faster emergency decisions.',
    technicalContext: 'Interactive computational dashboard synthesizing complex telemetry into prioritized operational directives for incident commanders.',
  },
  {
    term: 'Telemetry',
    category: 'System & Data',
    simpleExplanation: 'Measurements collected automatically by sensors or remote computers and sent over the internet for display.',
    technicalContext: 'Automated data streaming of remote observations (rainfall, moisture, temperature) transmitted via REST APIs to processing servers.',
  },
  {
    term: 'Real-time / Live Data',
    category: 'System & Data',
    simpleExplanation: 'Information that is delivered and updated immediately as it happens in the real world (such as current rainfall from Open-Meteo).',
    technicalContext: 'Data queried and processed from external live APIs during current application runtime with minimal latency.',
  },
  {
    term: 'Static Dataset',
    category: 'System & Data',
    simpleExplanation: 'Information that was gathered beforehand and saved in the database (like historical landslides or mountain elevation maps).',
    technicalContext: 'Pre-compiled, curated baseline records stored in Supabase PostgreSQL or local JSON files without continuous streaming alteration.',
  },
  {
    term: 'Calculated Data',
    category: 'System & Data',
    simpleExplanation: 'Values created by LANDGUARD AI using its own mathematical formulas (such as the 0–100 risk score and proximity buffers).',
    technicalContext: 'Outputs generated deterministically by the application’s physical-empirical algorithms from raw input streams.',
  },
  {
    term: 'Demo Data',
    category: 'System & Data',
    simpleExplanation: 'Simulated, artificial data used during training or presentations to show how the system responds to a sudden cloudburst.',
    technicalContext: 'Synthesized telemetry injected via `/api/demo/trigger` to demonstrate end-to-end alert escalation without real-world hazard events.',
  },
  {
    term: 'Optional Feature',
    category: 'System & Data',
    simpleExplanation: 'A capability (like Gemini AI natural language answers) that turns on if an API key is provided, but uses a deterministic fallback if omitted.',
    technicalContext: 'Service modules that activate when supplementary credentials exist in the environment, falling back safely without system failure.',
  },
  {
    term: 'API / REST API',
    category: 'System & Data',
    simpleExplanation: 'Application Programming Interface — a standard way for different computer programs to talk to each other over the web.',
    technicalContext: 'HTTP-based Representational State Transfer endpoints accepting JSON payloads and returning standardized data responses.',
  },
  {
    term: 'Supabase & PostgreSQL',
    category: 'System & Data',
    simpleExplanation: 'The relational database where LANDGUARD AI stores monitored locations, weather history, historical slide catalogues, and risk logs.',
    technicalContext: 'Enterprise-grade open-source SQL database with Row Level Security (RLS), spatial indexing, and Realtime WebSocket replication.',
  },
  {
    term: 'Row Level Security (RLS)',
    category: 'System & Data',
    simpleExplanation: 'Security rules in the database that guarantee users can only read or edit data they are authorized to touch.',
    technicalContext: 'PostgreSQL access policies evaluating the executing user’s role and claims per table row to prevent unauthorized data manipulation.',
  },
  {
    term: 'Leaflet, OpenStreetMap & CartoDB',
    category: 'Geospatial',
    simpleExplanation: 'The open-source interactive mapping library and free street map tiles used to render the GIS command map.',
    technicalContext: 'Client-side raster tile slippy map engine loading open cartographic vector-rendered tiles under open access licenses.',
  },
  {
    term: 'Open-Meteo',
    category: 'Hydrology',
    simpleExplanation: 'A free, open-access meteorological service providing real-time hourly rainfall, forecast models, and humidity without requiring paid API keys.',
    technicalContext: 'High-availability public numerical weather prediction (NWP) API serving aggregated GFS and ECMWF model interpolations.',
  },
];

export const AboutView: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');

  const filteredGlossary = GLOSSARY_TERMS.filter((item) => {
    const matchesSearch =
      item.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.simpleExplanation.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.technicalContext.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCat = selectedCategory === 'ALL' || item.category === selectedCategory;
    return matchesSearch && matchesCat;
  });

  const categories = ['ALL', 'Risk Analysis', 'Geospatial', 'Hydrology', 'Geology', 'System & Data'];

  return (
    <div className="max-w-5xl mx-auto space-y-10 pb-20">
      {/* Header */}
      <div className="border-b border-slate-800 pb-4">
        <span className="text-xs font-mono font-bold uppercase tracking-wider text-cyan-400">
          TRANSPARENCY & SCIENTIFIC RIGOR
        </span>
        <h1 className="text-2xl sm:text-3xl font-black text-white tracking-tight font-display mt-0.5">
          METHODOLOGY, MATHEMATICAL MODEL & GLOSSARY
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          Detailed technical specifications, input datasets, empirical susceptibility weights, data truth audits, and full glossary of LANDGUARD AI
        </p>
      </div>

      {/* Scientific Positioning Section */}
      <section className="p-6 rounded-2xl bg-amber-950/20 border border-amber-500/40 space-y-3">
        <div className="flex items-center gap-2 text-amber-400 font-bold text-base">
          <AlertTriangle className="w-5 h-5 shrink-0" />
          <span>Scientific Positioning & Operational Scope</span>
        </div>
        <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
          LANDGUARD AI does <strong>NOT</strong> claim to forecast the exact minute or second an individual rock or debris mass will detach from a slope. Landslides in the North Eastern Himalayas are complex geotechnical failures driven by progressive microscopic shear strains, sub-surface joint water pressures, and toe undercutting.
        </p>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          Instead, LANDGUARD AI delivers <strong>dynamic landslide susceptibility assessment, environmental hotspot clustering, and early-warning decision support</strong>. It identifies where physical conditions (moisture saturation + critical incline + fragile geology) elevate the probability of failure, cross-references nearby human settlements and highways, and prioritizes preventative intervention by disaster management authorities.
        </p>
      </section>

      {/* PHASE 3: DATA STATUS MODEL SPECIFICATION */}
      <section className="p-6 rounded-2xl bg-slate-900 border border-slate-800 space-y-4">
        <div className="flex items-center gap-2 text-cyan-400 font-bold text-base font-display uppercase tracking-wide">
          <Radio className="w-5 h-5 shrink-0" />
          <span>LANDGUARD AI Data Status Classification Model</span>
        </div>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          To maintain technical honesty and prevent misleading claims, every data point in LANDGUARD AI is explicitly assigned one of five verified concepts:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 pt-2">
          <div className="p-3.5 rounded-xl bg-slate-950/80 border border-emerald-500/30 space-y-1.5">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
              LIVE
            </span>
            <div className="text-xs font-bold text-white pt-1">Runtime External API</div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Data fetched from an external service during application operation (e.g. real-time precipitation and 72-hr antecedent moisture from Open-Meteo).
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-950/80 border border-blue-500/30 space-y-1.5">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-blue-500/20 text-blue-300 border border-blue-500/40">
              DATASET
            </span>
            <div className="text-xs font-bold text-white pt-1">Imported / Stored Records</div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Previously collected and verified data stored locally or in Supabase (e.g. SRTM/ASTER 30m DEM terrain, GSI NLSM historical slides, OSM infrastructure nodes).
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-950/80 border border-indigo-500/30 space-y-1.5">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-indigo-500/20 text-indigo-300 border border-indigo-500/40">
              CALCULATED
            </span>
            <div className="text-xs font-bold text-white pt-1">Proprietary Algorithms</div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Values generated dynamically by LANDGUARD AI using its own mathematical equations (e.g. multi-factor risk score 0–100, hotspot flag, 2.5km impact buffer analysis).
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-950/80 border border-amber-500/30 space-y-1.5">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-500/20 text-amber-300 border border-amber-500/40">
              DEMO
            </span>
            <div className="text-xs font-bold text-white pt-1">Simulated Drill Scenario</div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Artificial test data used only for emergency drill demonstrations (e.g. one-click 34.6 mm/h cloudburst surge in Gangtok to verify end-to-end alert dispatch).
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-950/80 border border-purple-500/30 space-y-1.5 sm:col-span-2 lg:col-span-2">
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-purple-500/20 text-purple-300 border border-purple-500/40">
              OPTIONAL
            </span>
            <div className="text-xs font-bold text-white pt-1">Keyed Capability with Fallback</div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Advanced features enabled when optional credentials are provided (e.g. Google Gemini 3.8 Flash for grounded natural language Q&amp;A). If the key is omitted, the system falls back to a deterministic rule engine without errors.
            </p>
          </div>
        </div>
      </section>

      {/* PHASE 2: DATA SOURCE TRUTH AUDIT */}
      <section className="space-y-4">
        <h2 className="text-lg font-bold text-white font-display uppercase tracking-wide flex items-center gap-2">
          <Database className="w-5 h-5 text-cyan-400" />
          Data Source Truth Audit & Distinctions
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-2 text-sky-400 font-bold text-sm">
                <CloudRain className="w-4 h-4" /> 1. Weather Telemetry (Open-Meteo)
              </span>
              <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                LIVE
              </span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              <strong>Actual Implementation:</strong> Live HTTP API requests to Open-Meteo Global Forecasting endpoints every 15 minutes. No API key required.
            </p>
            <div className="text-[11px] text-slate-400">
              Captures current precipitation rate (mm/h) and 72-hour antecedent rainfall (mm). Fallback: regional climatological average during connection drops.
            </div>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-2 text-amber-400 font-bold text-sm">
                <Mountain className="w-4 h-4" /> 2. Terrain & Slope (SRTM / ASTER)
              </span>
              <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-blue-500/20 text-blue-300 border border-blue-500/40">
                DATASET
              </span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              <strong>Actual Implementation:</strong> Static terrain dataset derived from NASA SRTM and ASTER 30-meter Digital Elevation Models.
            </p>
            <div className="text-[11px] text-slate-400">
              Not a live satellite downlink. Slope gradient (°), aspect, and Terrain Ruggedness Index (TRI) are pre-derived and indexed in the database.
            </div>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-2 text-purple-400 font-bold text-sm">
                <History className="w-4 h-4" /> 3. Historical Landslides (GSI NLSM)
              </span>
              <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-blue-500/20 text-blue-300 border border-blue-500/40">
                DATASET
              </span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              <strong>Actual Implementation:</strong> Historical GSI-derived landslide dataset from National Landslide Susceptibility Mapping and NDMA records.
            </p>
            <div className="text-[11px] text-slate-400">
              Not a live GSI real-time telemetry feed. Curated spatial inventory of historical events stored in Supabase with Haversine distance decay modeling.
            </div>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-2 text-emerald-400 font-bold text-sm">
                <ShieldCheck className="w-4 h-4" /> 4. Infrastructure Exposure (OSM)
              </span>
              <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-blue-500/20 text-blue-300 border border-blue-500/40">
                DATASET
              </span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              <strong>Actual Implementation:</strong> OSM-derived infrastructure dataset mapped to regional mountain highway and settlement nodes.
            </p>
            <div className="text-[11px] text-slate-400">
              Not a live Overpass OSM API query on each page view. Assets are stored and queried using a local 2.5km radial proximity buffer.
            </div>
          </div>
        </div>
      </section>

      {/* PHASE 4: RISK CALCULATION SPECIFICATION */}
      <section className="p-6 rounded-2xl bg-slate-900 border border-slate-800 space-y-4">
        <h2 className="text-lg font-bold text-white font-display uppercase tracking-wide flex items-center gap-2">
          <Code2 className="w-5 h-5 text-cyan-400" />
          Transparent Risk Calculation & Prototype Weights
        </h2>

        <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/30 text-xs text-amber-200">
          <strong>Transparency Notice:</strong> Weights are labeled as <em>"Prototype empirical/configurable weights"</em> based on regional Himalayan hazard literature. They are not claimed to be universally validated geotechnical truths and can be tuned via the Thresholds API.
        </div>

        <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 font-mono text-xs sm:text-sm text-cyan-300 overflow-x-auto">
          <code>
            Composite_Score (0–100) = (0.35 × Rainfall) + (0.30 × Slope) + (0.20 × Historical) + (0.15 × Terrain)
          </code>
        </div>

        {/* 4 Factor Normalization Tables */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs text-slate-300">
          <div className="p-3.5 rounded-lg bg-slate-950/70 border border-slate-800/80 space-y-1.5">
            <div className="flex items-center justify-between text-sky-400 font-bold">
              <span>1. Rainfall Factor (Weight: 35%)</span>
              <span className="font-mono text-[11px]">0–100</span>
            </div>
            <p className="text-slate-400">
              Combines instantaneous rainfall rate (40% weight, saturated at 20 mm/h) and 72-hour antecedent rainfall (60% weight, saturated at 180 mm).
            </p>
            <div className="font-mono text-[10px] text-slate-500">
              Formula: min(100, (Rain_1h / 20)×100)×0.4 + min(100, (Rain_72h / 180)×100)×0.6
            </div>
          </div>

          <div className="p-3.5 rounded-lg bg-slate-950/70 border border-slate-800/80 space-y-1.5">
            <div className="flex items-center justify-between text-amber-400 font-bold">
              <span>2. Slope Factor (Weight: 30%)</span>
              <span className="font-mono text-[11px]">0–100</span>
            </div>
            <p className="text-slate-400">
              Piecewise normalization based on critical angle of repose: &lt;15° (0–25 score), 15–28° (25–50 score), 29–38° (51–75 score), &gt;38° (76–100 score).
            </p>
            <div className="font-mono text-[10px] text-slate-500">
              Piecewise linear interpolation over discrete incline intervals.
            </div>
          </div>

          <div className="p-3.5 rounded-lg bg-slate-950/70 border border-slate-800/80 space-y-1.5">
            <div className="flex items-center justify-between text-purple-400 font-bold">
              <span>3. Historical Activity (Weight: 20%)</span>
              <span className="font-mono text-[11px]">0–100</span>
            </div>
            <p className="text-slate-400">
              Spatial proximity decay to nearest verified GSI slip plane: ≤2.5 km (92 pts), ≤6 km (78 pts), ≤15 km (58 pts), ≤30 km (38 pts), plus frequency bonus (+3 pts per slide in 15 km).
            </p>
            <div className="font-mono text-[10px] text-slate-500">
              Haversine geodesic distance calculation with spatial decay.
            </div>
          </div>

          <div className="p-3.5 rounded-lg bg-slate-950/70 border border-slate-800/80 space-y-1.5">
            <div className="flex items-center justify-between text-emerald-400 font-bold">
              <span>4. Terrain &amp; Lithology (Weight: 15%)</span>
              <span className="font-mono text-[11px]">0–100</span>
            </div>
            <p className="text-slate-400">
              Weights Terrain Ruggedness Index (40%), rock mechanics fragility (35%, e.g. phyllite/shale = 85, granite = 40), and vegetation loss penalty (25%).
            </p>
            <div className="font-mono text-[10px] text-slate-500">
              Score = (TRI × 0.4) + (Lithology × 0.35) + (Vegetation × 0.25)
            </div>
          </div>
        </div>

        {/* Risk Classification Bands */}
        <div className="pt-2">
          <div className="text-xs font-bold text-slate-200 uppercase font-mono mb-2">
            Classification Thresholds:
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono">
            <div className="p-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-300">
              <div className="font-bold">LOW</div>
              <div className="text-[11px] text-emerald-400/80">0 – 25</div>
            </div>
            <div className="p-2.5 rounded-lg bg-yellow-500/10 border border-yellow-500/30 text-yellow-300">
              <div className="font-bold">MODERATE</div>
              <div className="text-[11px] text-yellow-400/80">26 – 50</div>
            </div>
            <div className="p-2.5 rounded-lg bg-orange-500/10 border border-orange-500/30 text-orange-300">
              <div className="font-bold">HIGH</div>
              <div className="text-[11px] text-orange-400/80">51 – 75</div>
            </div>
            <div className="p-2.5 rounded-lg bg-rose-500/10 border border-rose-500/30 text-rose-300">
              <div className="font-bold">CRITICAL</div>
              <div className="text-[11px] text-rose-400/80">76 – 100</div>
            </div>
          </div>
        </div>
      </section>

      {/* PHASE 5: INTERACTIVE GLOSSARY / TERMS EXPLAINED */}
      <section className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div>
            <h2 className="text-lg font-bold text-white font-display uppercase tracking-wide flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-cyan-400" />
              Glossary / Terms Explained
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Clear, simple explanations for every technical, geospatial, hydrological, and system term used in LANDGUARD AI
            </p>
          </div>
          <div className="text-xs text-cyan-400 font-mono">
            {filteredGlossary.length} of {GLOSSARY_TERMS.length} Terms
          </div>
        </div>

        {/* Search & Filter Bar */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
          <div className="relative flex-1">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search any term (e.g. TRI, Phyllite, DEM, Antecedent, Telemetry)..."
              className="w-full bg-slate-900 border border-slate-800 rounded-lg pl-9 pr-4 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500"
            />
          </div>

          <div className="flex flex-wrap gap-1">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setSelectedCategory(cat)}
                className={`px-2.5 py-1.5 rounded-lg text-xs font-mono transition cursor-pointer ${
                  selectedCategory === cat
                    ? 'bg-cyan-600 text-white font-bold'
                    : 'bg-slate-900 hover:bg-slate-800 text-slate-400 border border-slate-800'
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* Glossary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 max-h-[640px] overflow-y-auto pr-1">
          {filteredGlossary.map((item) => (
            <div
              key={item.term}
              className="p-4 rounded-xl bg-slate-900/90 border border-slate-800/80 hover:border-slate-700 space-y-2 transition flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between gap-2">
                  <h3 className="font-bold text-sm text-cyan-300 font-display">
                    {item.term}
                  </h3>
                  <span className="px-2 py-0.5 rounded text-[9px] font-mono font-bold bg-slate-800 text-slate-400 border border-slate-700 shrink-0">
                    {item.category}
                  </span>
                </div>
                <p className="text-xs text-slate-200 mt-1 leading-relaxed">
                  {item.simpleExplanation}
                </p>
              </div>
              <div className="text-[10px] text-slate-400 font-mono pt-2 border-t border-slate-800/70 italic">
                <span className="text-slate-500 font-semibold not-italic">Technical: </span>
                {item.technicalContext}
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};
